### ISSUE TITLE
Unable to add third chart in the dashboard.

### ISSUE THREAD

**Issue by senthilkumar2githup** [senthilkumar2githup/Dashboard#42]
Error shown as unable to modify the composition.

java.lang.Exception: Specified field abbreviation for Contract DefaultHIPIERepo.admin.VXI is not available in dataset dsInput1(^Ins001|dsOutput). Available dataset fields:  STRING productcode , STRING productname , STRING productline , STRING productscale , STRING productvendor , STRING productdescription , INTEGER8 quantityinstock , DECIMAL10_3 buyprice , STRING msrp
    at org.hpccsystems.dashboard.service.impl.CompositionServiceImpl.validateSaveCompositionContract(CompositionServiceImpl.java:433)
    at org.hpccsystems.dashboard.service.impl.CompositionServiceImpl.addCompositionChart(CompositionServiceImpl.java:107)
    at org.hpccsystems.dashboard.service.impl.CompositionServiceImpl$$FastClassBySpringCGLIB$$710ba6ca.invoke(<generated>)

**Comment by RajalakshmiElumalaiCts** [comment]
Unable to recreate
